CREATE TABLE Event (Event_ID VARCHAR(10) PRIMARY KEY, 
Event_name VARCHAR(20), Date_Time TIMESTAMP, Status VARCHAR(10), 
Venue_ID VARCHAR(10), FOREIGN KEY (Venue_ID) REFERENCES Venue);

CREATE TABLE Student(Roll_no VARCHAR(10) PRIMARY KEY ,
Name VARCHAR(20), Email VARCHAR(30), Committee VARCHAR(10), 
Year INTEGER, Phone INTEGER);

CREATE TABLE Judge(Judge_ID VARCHAR(10) PRIMARY KEY , 
Name VARCHAR(20), Event_ID VARCHAR(10), 
FOREIGN KEY (Event_ID) REFERENCES Event);

CREATE TABLE Participants(Pid VARCHAR(10) PRIMARY KEY , 
Phone INTEGER, College VARCHAR(20), Name VARCHAR(20));

CREATE TABLE Winners(Pid VARCHAR(10), Event_ID VARCHAR(10), 
Position INTEGER, Reception_status VARCHAR(1) DEFAULT 'n',  
PRIMARY KEY(Pid, Event_ID), FOREIGN KEY(Pid) REFERENCES 
Participants, FOREIGN KEY(Event_ID) REFERENCES Event);

CREATE TABLE Venue(Venue_ID VARCHAR(10) PRIMARY KEY, 
Venue_name VARCHAR(20), Faculty_incharge VARCHAR(20), 
Dept VARCHAR(10));

CREATE TABLE Participation ( Event_ID VARCHAR(10), 
Pid VARCHAR(10), PRIMARY KEY(Event_ID, Pid),
FOREIGN KEY(Event_ID) REFERENCES Event, 
FOREIGN KEY(Pid) REFERENCES Participants);


CREATE TABLE Works_on(Event_ID VARCHAR(10), Roll_no VARCHAR(10), 
PRIMARY KEY(Event_ID,Roll_no), FOREIGN KEY(Event_ID) 
REFERENCES Event, FOREIGN KEY(Roll_no) REFERENCES Student);

